# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-20 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0024_auto_20170102_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 20, 17, 25, 11, 788000), editable=False),
        ),
        migrations.AlterField(
            model_name='social',
            name='Link to profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 20, 17, 25, 11, 789000)),
        ),
    ]
